- name: install required nginx mod
  become: yes
  package:
    name: libnginx-mod-http-headers-more-filter

- name: hls directory
  become: yes
  file:
    state: directory
    path: /opt/hls

- name: compile vhost configuration file
  become: yes
  notify: reload-nginx
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/cdn_origin

- name: enable vhost configuration
  become: yes
  notify: reload-nginx
  file:
    state: link
    src: /etc/nginx/sites-available/cdn_origin
    dest: /etc/nginx/sites-enabled/cdn_origin
