---
- hosts: all
  roles:
    - common

- hosts: all
  roles:
    - no_snapd
    - ufw
    - acme_cert
    - node_exporter

- hosts: srs_origin
  roles:
    - srs_origin
  tags:
    - srs

- hosts: srs_edge
  roles:
    - srs_edge
  tags:
    - srs

- hosts: grafana
  roles:
    - grafana

- hosts: prometheus
  roles:
    - prometheus
