---
- name: install packages
  become: yes
  package:
    name:
      - certbot
      - python3-pip

- name: install hetzner dns plugin
  become: yes
  pip:
    executable: pip3
    name: certbot-dns-hetzner


- name: compile certbot config
  become: yes
  no_log: yes
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: 0600

- name: compile hetzner config
  become: yes
  no_log: yes
  template:
    src: hetzner.ini.j2
    dest: /etc/letsencrypt/hetzner.ini
    owner: root
    group: root
    mode: 0600

- name: enable automatic renewal
  become: yes
  cron:
    name: "certbot renew"
    cron_file: /etc/cron.d/certbot-renew
    user: root
    job: "/usr/bin/certbot renew > /dev/null"
    special_time: daily
