---
- name: compile edge server configuration
  become: yes
  template:
    src: srs.edge.conf.j2
    dest: /etc/srs.edge.conf

- name: container
  become: yes
  docker_container:
    name: srs_edge
    image: ossrs/srs:4
    pull: yes
    state: started
    restart_policy: unless-stopped
    network_mode: host
    keep_volumes: no
    volumes:
      - "/etc/srs.edge.conf:/usr/local/srs/conf/docker.conf:ro"

- name: open rtmp playout firewall port
  become: yes
  ufw:
    rule: allow
    proto: tcp
    port: "{{ srs_edge_rtmp_port }}"
