- name: install package
  become: yes
  apt:
    name: prometheus-node-exporter

- name: template prometheus-node-exporter file
  become: yes
  notify: restart-prometheus-node-exporter
  template:
    src: prometheus-node-exporter.j2
    dest: /etc/default/prometheus-node-exporter

- name: enable and start services
  become: yes
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - prometheus-node-exporter

- name: open firewall for prometheus servers (v4)
  become: yes
  ufw:
    rule: allow
    port: '9100'
    proto: tcp
    src: "{{ item }}"
  loop: "{{ prometheus_ips_v4 }}"

- name: open firewall for prometheus servers (v6)
  become: yes
  ufw:
    rule: allow
    port: '9100'
    proto: tcp
    src: "{{ item }}"
  loop: "{{ prometheus_ips_v6 }}"
